### PR TITLE
Code and database change for issue #8

### PR DESCRIPTION
**Pull request by lordp**
I've updated the code in json.php as per Arjen's comments. I've tested this locally on a very sparse database (5 records), but it does seem to be making use of the 'incident_date' index.

### CODE REVIEW

**Comment by sminnee** [comment]
Do you know about git `add --patch` and/or GitX on the mac?  You can choose which pieces of a file you want to change.  Fun++.

**Comment by sminnee** [comment]
Are we able to do this without changing the database?  Database changes will introduce an outage on the site between updating the database and updating the code.

**Comment by lordp** [comment]
I think the database change is only for saving some storage space, so can probably be skipped.

**Comment by lordp** [comment]
A quick revert of the database change - the index is still used, only real difference is the key length is longer.

**Comment by nigelmcnie** [comment]
This pull requests has gone insane - 71 commits? Also, the whitespace changes make it hard to work out what exactly needs to be applied.

Would it be possible for a new pull request to be submitted with a smaller diff please?

**Comment by lordp** [comment]
Yeah, I had some issues merging upstream (bit of a git noob still)...

I've put the relevant patch lines into a gist -> https://gist.github.com/848632

**Pull request closed without merging**
