### PR TITLE
Minor UI Changes

### PR DESCRIPTION
**Pull request by serenecloud**
Removing the bold category mouseover and adding a hidden paragraph that I hope will show up on Facebook when the scrape the site for sharing.

### CODE REVIEW

**Comment by kampf** [comment]
Noted this on dev and that it made for strange behavior with word wrapped lines.

**Comment by serenecloud** [comment]
kampf: Are you referring to the fix or the original issue the fix is for?

I can't see my changes on dev.

**Comment by kampf** [comment]
Referring to the current behavior on dev.

**Comment by nigelmcnie** [comment]
Merged to master, thanks.

**Pull request merged**
