### PR TITLE
Improved Twitter filter

### PR DESCRIPTION
**Pull request by nickmalcolm**
After noticing a multitude of retweets I thought it might be good to add a filter. This is as basic as you can get I suppose, and is embeeded right into the search string used to get the JSON. You can test it out by pasting the search string in your browser, but I haven't written any unit or functional tests.

### CODE REVIEW

**Comment by rcoup** [comment]
https://github.com/ccnz/Ushahidi_Web/pull/13

see the comments there!

**Comment by rcoup** [comment]
after more discussion on IRC (ibeardslee, others):

people doing RT & adding #eqnz at the end would get blocked
ala "new thing happening" > "RT new thing happening #eqnz"

but maybe we can block RTs from other hashtags?

Also: being able to _exclude_ a sender (@eqnz_live) so we can use that as an update channel to the public.

**Comment by sminnee** [comment]
I'm not sure I understand this one sufficiently - should we just merge in pull request 13 as-is, or are will still unsure as to how to do this?

Presumably, the high-level goal is to ignore duplicates, so why don't we ignore the RT vs non-RT thing and just ignore any tweet that looks like it exists already in the DB?

What kind of throughput are we getting, roughly?

**Comment by nickmalcolm** [comment]
I'd say don't merge this. It's not an ideal solution. We need to come up with something more thorough which gets what we want (re rcoups comment), has been tested and, if possible, is easy enough to contribute back to others (e.g. is a plugin). I'm afraid I'm too busy at the moment to take the time to do this at the moment though :(

**Comment by rcoup** [comment]
140k tweets in the last 24h. Key goals:
- exclude some set of senders. we want to setup @eqnz_live to push out latest reports, but we don't want it recursing back into our inbox :) I think we can do this via `-from:eqnz_live` (but check the twitter search api docs)
- exclude messages starting with "RT " where the hashtag is not #eqnz (our primary one). Nick & I couldn't get this happening via the Search API (`-RT`) -- an RT anywhere in the message matched... so i think it needs PHP processing

**Comment by sminnee** [comment]
For now I've ignored eqnz_live, that first part of this.

I could do the "RT" exclusion tomorrow, in the PHP if needs be.

**Comment by rcoup** [comment]
we also need to be able to:
- ignore specific senders: @BrendaSawJESUS
- ignore combinations of hashtags (eg. `#eqnz #redandblack` in the same message)

**Comment by redspider** [comment]
Simply removing RT's doesn't seem like a good idea - the twitter feed doesn't pick up every message when volues get high or if ush is down for a bit or whatever. I tentatively suggest the following mechanism:

Retain two lookup tables and a hashing system. An example hashing algorithm is here:

https://gist.github.com/842862

Each tweet received gets hashed according to that, then looked up in a table. If the hash key has already been seen (either the original, or a different RT) it will already exist in the table so we drop the tweet, otherwise the tweet is added to the DB and the hash key is added to the lookup table.

The volume of tweets is not so large that storing keys for them all poses any problem right now, and it'd remove most duplicates.

**Comment by sminnee** [comment]
OK redspider, I've done something similar to what you've suggested in 360a52564df8bb0c77f71412ad7611f68a5d7c3d

The sender and combination hashtag restriction is still to come.  I might tweak the twitter config field so you can use it to specify any twitter search preferences.

Then we can set it something like this, and pass it straight through to twitter:

```
#christchurch #ChristchurchQuake #nzeq #eqnz -#redandblack -from:eqnz_live -from:BrendaSawJESUS
```

Does that make sense?

**Comment by sminnee** [comment]
Minor error there, I forgot to write OR:

```
#christchurch OR #ChristchurchQuake OR #nzeq OR #eqnz -#redandblack -from:eqnz_live -from:BrendaSawJESUS
```

See the results [here](http://search.twitter.com/search?q=%23christchurch+OR+%23ChristchurchQuake+OR+%23nzeq+OR+%23eqnz+-%23redandblack+-from:eqnz_live+-from:BrendaSawJESUS)

**Comment by redspider** [comment]
Looks good sminnee

**Comment by sminnee** [comment]
Sweet that is all on dev.eq.co.nz now.  Rob - I'll leave it up to you to deploy.

**Comment by nickmalcolm** [comment]
sminee, not sure your commit did what you wanted it to? Is it supposed to show up on the bottom right of the eq.org.nz page as below:

#### How to Report

  By sending a message to 5627
  By sending an email to eqnzfeb@gmail.com
  By sending a tweet with the hashtag/s #christchurch OR #ChristchurchQuake OR #nzeq OR #eqnz -#redandblack -#Red&Black -from:eqnz_live -from:BrendaSawJESUS
  By filling this form

**Comment by sminnee** [comment]
Oops! I missed the alternate use of this field :-(  Will fix.

**Comment by sminnee** [comment]
Fixed in 05b5f815294341681624c67371d5587b76485683 - still needs to be published.

**Pull request closed without merging**
